const mongoose = require('mongoose');

const ChairSchema = new mongoose.Schema({
    chair: { type: String, default: 'without' },
    email: { type: String, default: '' },
    phone: { type: String, default: '' },
    address: { type: String, default: '' },
    name: { type: String, default: '' },
    inTime: { type: String, default: '' },
    outTime: { type: String, default: '' },
    busNumber: { type: String, default: '' },
    form: { type: String, default: '' },
    to: { type: String, default: '' },
    date: { type: String, default: '' },
});

const ProductSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
    },
    price: {
        type: Number,
        required: true,
    },
    description: {
        type: String,
        required: true,
    },
    category: {
        type: String,
        required: true,
    },
    image: {
        type: String,
        required: true,
    },
    date: {
        type: String,
    },
    time: {
        type: String,
        default: new Date().toLocaleTimeString(),
    },
    quantity: {
        type: Number,
    },
    inTime: {
        type: String,
    },
    outTime: {
        type: String,
    },
    busNumber: {
        type: String,
    },
    form: {
        type: String,
    },
    to: {
        type: String,
    },
    chairAll: {
        type: [ChairSchema],
        default: [
            {
                chair1: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair2: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair3: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair4: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair5: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair6: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair7: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair8: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair9: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair10: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair11: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair12: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair13: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair14: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair15: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair16: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair17: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair18: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair19: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair20: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair21: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair22: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair23: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair24: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair25: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair26: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair27: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair28: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair29: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair30: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair31: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair32: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair33: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair34: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair35: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair36: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair37: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair38: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair39: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair40: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair41: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
            {
                chair42: false,
                email: '',
                phone: '',
                address: '',
                name: '',
                InTime: '',
                OutTime: '',
                busNumber: '',
                form: '',
                to: '',
                date: '',
            },
        ],
    },
});

const Product = mongoose.model('Product', ProductSchema);

module.exports = Product;
